"use client"

import CategoryLayout from "../../components/CategoryLayout"

const trendingArticlesData = [
  {
    id: 1,
    title: "Viral Fashion Trends Taking Over Social Media",
    slug: "viral-fashion-trends-social-media",
    image: "https://picsum.photos/300/360?random=111",
    author: "Social Media Team",
    date: "December 22, 2024",
    category: "Trending",
    excerpt: "The fashion trends that are breaking the internet right now...",
  },
  {
    id: 2,
    title: "Celebrity Style Moments That Went Viral",
    slug: "celebrity-style-moments-viral",
    image: "https://picsum.photos/300/360?random=112",
    author: "Style Reporter",
    date: "December 20, 2024",
    category: "Trending",
    excerpt: "Red carpet looks and street style that captured everyone's attention...",
  },
  {
    id: 3,
    title: "Tech Gadgets Everyone's Talking About",
    slug: "tech-gadgets-everyone-talking",
    image: "https://picsum.photos/300/360?random=113",
    author: "Tech Reviewer",
    date: "December 18, 2024",
    category: "Trending",
    excerpt: "The latest tech innovations creating buzz in the market...",
  },
  {
    id: 4,
    title: "Wellness Trends Dominating 2025",
    slug: "wellness-trends-dominating-2025",
    image: "https://picsum.photos/300/360?random=114",
    author: "Wellness Expert",
    date: "December 16, 2024",
    category: "Trending",
    excerpt: "Health and wellness practices that are gaining massive popularity...",
  },
  {
    id: 5,
    title: "Food Trends: What's Hot in Culinary World",
    slug: "food-trends-hot-culinary-world",
    image: "https://picsum.photos/300/360?random=115",
    author: "Food Critic",
    date: "December 14, 2024",
    category: "Trending",
    excerpt: "Culinary innovations and food trends taking over restaurants...",
  },
  {
    id: 6,
    title: "Travel Destinations Going Viral",
    slug: "travel-destinations-going-viral",
    image: "https://picsum.photos/300/360?random=116",
    author: "Travel Blogger",
    date: "December 12, 2024",
    category: "Trending",
    excerpt: "Hidden gems and popular destinations trending on social media...",
  },
  {
    id: 7,
    title: "Beauty Trends: Makeup Looks Everyone's Copying",
    slug: "beauty-trends-makeup-looks-copying",
    image: "https://picsum.photos/300/360?random=117",
    author: "Beauty Guru",
    date: "December 10, 2024",
    category: "Trending",
    excerpt: "The beauty looks and techniques going viral on beauty platforms...",
  },
  {
    id: 8,
    title: "Lifestyle Hacks That Actually Work",
    slug: "lifestyle-hacks-actually-work",
    image: "https://picsum.photos/300/360?random=118",
    author: "Lifestyle Coach",
    date: "December 8, 2024",
    category: "Trending",
    excerpt: "Practical life hacks that are changing how people live...",
  },
  {
    id: 9,
    title: "Another Trend",
    slug: "another-trend",
    image: "https://picsum.photos/300/360?random=119",
    author: "Trend Setter",
    date: "December 6, 2024",
    category: "Trending",
    excerpt: "A new trend on the rise...",
  },
  {
    id: 10,
    title: "Yet Another Trend",
    slug: "yet-another-trend",
    image: "https://picsum.photos/300/360?random=120",
    author: "Trend Watcher",
    date: "December 4, 2024",
    category: "Trending",
    excerpt: "Keeping up with the latest...",
  },
  {
    id: 11,
    title: "One More Trend",
    slug: "one-more-trend",
    image: "https://picsum.photos/300/360?random=121",
    author: "Trend Analyst",
    date: "December 2, 2024",
    category: "Trending",
    excerpt: "Analyzing the trend landscape...",
  },
  {
    id: 12,
    title: "The Last Trend",
    slug: "the-last-trend",
    image: "https://picsum.photos/300/360?random=122",
    author: "Trend Forecaster",
    date: "November 30, 2024",
    category: "Trending",
    excerpt: "Forecasting future trends...",
  },
  {
    id: 13,
    title: "Extra Trend 1",
    slug: "extra-trend-1",
    image: "https://picsum.photos/300/360?random=123",
    author: "Trend Expert",
    date: "November 28, 2024",
    category: "Trending",
    excerpt: "More trends to explore...",
  },
  {
    id: 14,
    title: "Extra Trend 2",
    slug: "extra-trend-2",
    image: "https://picsum.photos/300/360?random=124",
    author: "Trend Enthusiast",
    date: "November 26, 2024",
    category: "Trending",
    excerpt: "Enjoying the trend wave...",
  },
]

export default function TrendingPage() {
  return (
    <CategoryLayout
      categoryName="Trending"
      categorySlug="trending"
      description="Stay ahead of the curve with the latest trends in fashion, lifestyle, technology, and culture that everyone's talking about."
    />
  )
}
